baseURL: "https://www.brain-dump.xyz"
languageCode: "en"
defaultContentLanguage: "en"
title: "Eldaroth's Brain Dump"
theme: "beautifulhugo"
enableGitInfo: false
pygmentsStyle: "trac"
pygmentsCodeFences: true
pygmentsUseClasses: true

params:
  subtitle: "Dumping ground for my thoughts and ideas on various topics"
  enableEmojis: true
  mainSections:
  - "post"
  commit: "https://github.com/Eldaroth/brain-dump-blog/commits/main"
  lastmod: false
  #favicon: "img/*.ico"
  #logo: "img/*.png"
  rss: true
  socialShare: true
  #readingTime: true
  #wordCount: true
  # bigimg:
    # src: "img/sphere.jpg"
    # desc: "Sphere"
      # # position: see values of CSS background-position.
      # # position: "center top"

author:
  name: "Flavio"
  website: "brain-dump.xyz"
  email: "eldaroth@protonmail.com"
  github: "Eldaroth"
  mastodon: "techhub.social/@eldaroth"

menu:
  main:
  - identifier: "blog"
    name: "blog"
    url: ""
    weight: 1
#  - identifier: "about"
#    name: "about"
#    url: "page/about/"
#    weight: 10
#  - identifier: "contact"
#    name: "contact"
#    url: "page/contact/"
#    weight: 20
  - identifier: "tags"
    name: "tags"
    url: "tags/"
    weight: 40

  # Topics Submenus
  - identifier: "topics"
    name: "topics"
    weight: 30
  - parent: "topics"
    name: "picoctf"
    url: "post/picoctf/"
    weight: 3
  - parent: "topics"
    name: "linux"
    url: "post/linux/"
    weight: 2
  - parent: "topics"
    name: "cloud"
    url: "post/cloud/"
    weight: 1